services:
  frontend:
    build: ./
    container_name: 2025_trip_explorer-frontend
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      # One-way volume to use node_modules from inside image
      - node-modules-trip-explorer:/app/node_modules
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - 2025_trip_explorer
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: 2025_trip_explorer-backend
    volumes:
      - ./backend:/app
      - ./public/markers:/app/public/markers
      - node-modules-backend:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trip_explorer
      - POSTGRES_HOST=postgres
    networks:
      - 2025_trip_explorer
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: 2025_trip_explorer-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trip_explorer
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/src/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - 2025_trip_explorer

networks:
  2025_trip_explorer:

volumes:
  node-modules-trip-explorer:
  node-modules-backend:
  postgres-data:
